[build]
  command = "npm run build:prod"
  publish = "dist/hedge-accounting-sfx"

[[redirects]]
  from = "/api/*"
  to = "https://3-91-170-95.nip.io/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/mcp/*"
  to = "https://3-91-170-95.nip.io/mcp/:splat"
  status = 200
  force = true

# SPA fallback so Angular routes work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

